### ISSUE TITLE
How to swap info on Primer Header

### ISSUE THREAD

**Issue by lyonsden10** [godaddy/wp-primer-theme#152]
Where do I go to either change the font size or switch the location of these lines. I want the top two lines to be bigger than the two bottom lines. So basically reversing the sizing. I can't just change the text because then the company name doesn't appear in the browser link.

Thanks for your help!

**Comment by EvanHerman** [comment]
Hi @lyonsden10 

You'll want to use CSS to alter the size of the font inside of the header. You can add custom styles to your site under the "Additional CSS" section of the customizer. 

From the dashboard if you go to 'Appearance > Customizer' and then click on "Additional CSS" you should see a new section appear where you can add the following code.

```css
body.home .hero . widget_text .widget-title {
   font-size: 1.2em;
}

body.home .hero . widget_text .textwidget p {
   font-size: 2em;
   font-weight: bold;
}
```

That should swap the styles associated with each of the elements in the header - and it will only affect them on the homepage.

**Comment by frankiejarrett** [comment]
@EvanHerman is this referring to swapping the Site Title & Tagline or the Hero widget Title & Text?

> I can't just change the text because then the company name doesn't appear in the browser link.

**Comment by lyonsden10** [comment]
I did it and nothing happened after saving.

**Comment by lyonsden10** [comment]
So I want the site title and tagline to be bigger and the Hero widget Title and text to be smaller (the part that says serving Broward...)

**Comment by lyonsden10** [comment]
Here is how my customizer looks:

/*
You can add your own CSS here.
Click the help icon above to learn more.
*/

/*Changing Site Title and Hero*/

body.home .hero . widget_text .widget-title {
   font-size: 1.2em;
}

body.home .hero . widget_text .textwidget p {
   font-size: 2em;
   font-weight: bold;
}

**Comment by lyonsden10** [comment]
Here is how my customizer looks

/*
You can add your own CSS here.


Click the help icon above to learn more.
*/

/*
Changing Site Title and Hero
*/

body.home .hero . widget_text .widget-title {
   font-size: 1.2em;
}

body.home .hero . widget_text .textwidget p {
   font-size: 2em;
   font-weight: bold;
}

**Comment by EvanHerman** [comment]
@lyonsden10 In your code above it looks like you have a space between the '.' and 'widget_text' which is why the styles are doing nothing on your end.

The above code will alter the styles of the widget text.

The change the styles of your site title and tag line you can also add:

```css

.site-title-wrapper h1 {
   font-size: 1em;
}

.site-title-wrapper .site-description {
   font-size: 1.25em;
}
```

You should be able to tweak them using px, em or rem values to better fit your site.

**Comment by lyonsden10** [comment]
No matter what I change (1em to 5em or change to px), it isn't changing. It's like it's not recognizing this to override the original stylesheet.

**Comment by lyonsden10** [comment]
YES! The space was the problem! Thank you so much 👍

**Comment by lyonsden10** [comment]
I truly appreciate the help of EvanHerman! Thanks as well to fjarrett in trying to clarify.

**Comment by EvanHerman** [comment]
@lyonsden10 No problem at all. Glad that we could help out and get you headed in the right direction!

**Comment by lyonsden10** [comment]
Sorry. The bottom two lines worked perfectly, but where do I find the code for the top two lines to make them larger? Is it in the Header.php file? Thanks

**Comment by EvanHerman** [comment]
Are you referring to the increasing the size of the top Title and Tagline?

Did you try the second block of code that I provided above?

```css
.site-title-wrapper h1 {
   font-size: 1em;
}

.site-title-wrapper .site-description {
   font-size: 1.25em;
}
```
