### ISSUE TITLE
Mobile SubMenus not Indenting in 1.7.0

### ISSUE THREAD

**Issue by SurfingDude** [godaddy/wp-primer-theme#201]
I am not getting the indents on sub and sub-sub menus, has there been some regression? I expect behavior like in the MeanMenu Demo but instead get a flat mobile menu.
 I'm using WordPress 4..3 on Godaddy with Primer 1.7.0 installed just this month, and I used the Child Theme Configurator By Lilaea Media to produce a child of Primer (I have yet not modified the Child Theme at all). My test site is:
http://test.enccert.org/
 Any help would be appreciated.
Note: I just posted this as a comment to #30 but is is closed so I am opening this new.

**Comment by EvanHerman** [comment]
Hi @SurfingDude 

I don't believe that the submenu items ever indented. The submenu items on mobile devices lie below the items with + next to them to indicate they are submenu items.

You can indent them using CSS by using styles similar to the theme. The following should help get you headed in the right direction.

```css
@media only screen and (max-width: 61.063em) {
   .main-navigation ul .open > .sub-menu > li > a {
      padding-left: 2em;
   }
}
```

**Comment by SurfingDude** [comment]
Hi Evan,

Thanks, that does what I need. Without your help I would have never known this.

      ...glen

**Comment by EvanHerman** [comment]
Not a problem at all, I'm glad that we could help out.

Have a great rest of your day!

**Comment by SurfingDude** [comment]
Hi Evan,

Small issue. That works OK, shows a +, for sub-menus. However, for sub-sub menus it does not show a +. Clicking on the right (which looks like blank space rather than a +) does bring up the sub-sub menus but not at any greater indentation.

Is this fixable? There’s some strong magic in this stuff all right...

      ...glen

**Comment by EvanHerman** [comment]
Hi @SurfingDude,

Sorry about that. I neglected to take that into account.

Here is a tweaked bit of code that should only target `:first-child` elements.

```css
@media only screen and (max-width: 61.063em) {
   .main-navigation ul .open > .sub-menu > li > a:first-child {
      padding-left: 2em;
   }
}
```
