### ISSUE TITLE
Removing some space in the menu display

### ISSUE THREAD

**Issue by atabhatti** [godaddy/wp-primer-theme#203]
I find the menu spacing to be too much on our site (www.sammamishmosque.com) and I would like to tighten it up.  I tried:

```
.main-navigation a {
  padding: 0.75rem 0.75rem;
}

```

But those changes to the CSS mess with the alignment of the '+' on mobile devices.  I am guessing that that there is computed CSS that I am not also adjusting which is causing this problem.  

So, how can I tighten up the menus on laptops as well as phones and tablets?

**Comment by EvanHerman** [comment]
Hi @atabhatti 

To tweak both the menu and the + sign on mobilde devices, the following should work:

```css
.main-navigation a {
  padding: 0.75rem 0.75rem;
}

.main-navigation .expand {
   padding: 12px;
}
```
