### ISSUE TITLE
Support for wide images in Gutenberg

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#239]
Add theme support for `wide-images`: https://wordpress.org/gutenberg/handbook/reference/theme-support/

Initial swag at the styles needed for Primer could be something like:

```css
.hentry {
	padding: 2.5em 0;
}

.hentry > *:not(.entry-content):not(.page-content),
.hentry > .entry-content > *:not(blockquote):not(.alignwide):not(.alignfull),
.hentry > .page-content > *:not(blockquote):not(.alignwide):not(.alignfull) {
	padding: 0 3.375em;
}

.hentry blockquote {
	margin-left: 3.375em;
	margin-right: 3.375em;
}

.hentry .alignwide,
.hentry .alignfull {
	padding-left: 0;
	padding-right: 0;
}

.hentry .alignfull {
	margin-left: 0;
	margin-right: 0;
}
```
